export enum ORDER_STATUS {
  ORDER_PENDING = "ORDER_PENDING",
  ORDER_PLACED = "ORDER_PLACED",
  ORDER_FAILED = "ORDER_FAILED", // DUE TO PAYMENT FAILED BY ANY REASON
  ORDER_CANCELLED = "ORDER_CANCELLED",
  ORDER_SHIPPED = "ORDER_SHIPPED",
  ORDER_COMPLETED = "ORDER_COMPLETED",
  ORDER_DELIVERED = "ORDER_DELIVERED",
  ORDER_PARTIALLY_DELIVERED = "ORDER_PARTIALLY_DELIVERED", // WHEN LARGE QTY ORDER SHIPPED WITH MORE THAN 1 TRACKING ID
  ORDER_PROCESSING = "ORDER_PROCESSING",
}
