enum PaymentMethod {
  CARD = "CARD",
  PAYPAL = "PAYPAL",
}
export const CheckoutFormDefaultValues = {
  paymentMethod: PaymentMethod.CARD,
  billingFirstName: "",
  billingLastName: "",
  billingCompanyName: "",
  billingPhone: "",
  billingStreetAddress: "",
  billingCity: "",
  billingState: "",
  billingZipCode: "",
  billingCountry: "United States",
  shippingSameAsBilling: true,
  shippingFirstName: "",
  shippingLastName: "",
  shippingCompanyName: "",
  shippingPhone: "",
  shippingStreetAddress: "",
  shippingCity: "",
  shippingState: "",
  shippingZipCode: "",
  shippingCountry: "United States",
};

export const US_STATES = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];
